---
title: "Music Insights"
author: "Nathan Lovell"
output: html_notebook

---


First, we need tidyverse to handle data imprting and wragling...
Then we can load datasets into variables for use later

```{r}
install.packages("tidyverse")
library("tidyverse")
library("dplyr")
library("tidyr")
survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv") #avoid absolute paths
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

```


Rename columns of survey
```{r}
colnames(survey)[colnames(survey) == "Timestamp"] <- "time_submitted"
colnames(survey)[colnames(survey) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"
colnames(survey)[colnames(survey) == "What is your pseudonym?"] <- "pseudonym"
colnames(survey)[colnames(survey) == "Sex"] <- "sex"
colnames(survey)[colnames(survey) == "Major"] <- "academic_major"
colnames(survey)[colnames(survey) == "Academic Year"] <- "academic_level"
colnames(survey)[colnames(survey) == "Year you were born (YYYY)"] <- "year_born"
colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"
colnames(survey)[colnames(survey) == "Artist"] <- "favorite_song_artist"
colnames(survey)[colnames(survey) == "Song"] <- "favorite_song"
colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"
colnames(survey)
```

Creating a Person Table

```{r}
Person <- tibble(pseudonym=survey$pseudonym, sex=survey$sex, academic_major=survey$academic_major, academic_level=survey$academic_level, year_born=survey$year_born, pseudonym_generator=survey$pseudonym_generator, time_submitted=survey$time_submitted)
colnames(Person)
```

Creating a Favorite Song table

```{r}
Favorite_Song <- tibble(pseudonym=survey$pseudonym, favorite_song=survey$favorite_song, song_artist=survey$favorite_song_artist, song_link=survey$favorite_song_link)
colnames(Favorite_Song)
```
